language: ruby
services:
- docker
env:
- SERVER_IP_ADDRESS=dev.moysklad.ru APP_PREFIX=api-remap-1.1
branches:
  only:
  - master
script:
- docker build . --tag aglio
- "./build.sh"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet output/ app@${SERVER_IP_ADDRESS}:./${APP_PREFIX}
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_8384e8f722f0_key -iv $encrypted_8384e8f722f0_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host ${SERVER_IP_ADDRESS}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key app@${SERVER_IP_ADDRESS} pwd
- rm deploy_key.enc deploy_key
