# Group Серийный номер
## Серийные номера [/entity/thing]
Средствами JSON API можно запрашивать списки Серийных номеров и сведения по отдельным Серийным номерам. Кодом сущности для Серийного номера в составе JSON API является ключевое слово **thing**.

### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о Серийном номере
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **name** - Наименование Серийного номера `Необходимое`
+ **description** - Описание Серийного номера

### Атрибуты доступные для фильтрации
+ **name** - Наименование Серийного номера `Необходимое`

### Атрибуты доступные для сортировки
+ **name** - Наименование Серийного номера `Необходимое`

### Получить Серийные номера [GET]
Запрос на получение списка всех Серийных номеров для данной учетной записи.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой Серийные номера.

+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Серийных номеров.
  + Body
        <!-- include(body/thing/get_list.json) -->

## Серийный номер [/entity/thing/{id}]
+ Parameters
  + id: `3840d8d8-9f2d-11ee-8c90-0242ac120002` (required, string) - id Серийного номера

## Получить Серийный номер [GET]
Запрос на получение серийного номера с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Серийного номера с указанным id.
  + Body
        <!-- include(body/thing/get_by_id.json) -->
