name: Build

on: push

jobs:
  date-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test dates in CHANGELOG.md
        run:
          cat CHANGELOG.md | egrep '^#+ +[0-9-]+' | sed -r 's/([0-9]+)-([0-9]+)-([0-9]+)/\3-\2-\1/g' | sort --check -nr;

  build:
    runs-on: ubuntu-latest
    needs: date-check
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          ./build.sh

      - name: Deploy
        env:
          SERVER_IP_ADDRESS: ${{ secrets.SERVER_IP_ADDRESS }}
          SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
          APP_PREFIX: api-remap-1.1
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          touch ~/.ssh/config && chmod 600 ~/.ssh/config
          echo -e "Host ${SERVER_IP_ADDRESS}\n\tStrictHostKeyChecking no\nPort ${SERVER_SSH_PORT}\n" >> ~/.ssh/config
          ssh-add - <<< "$DEPLOY_KEY"
          ssh app@${SERVER_IP_ADDRESS} pwd
          rsync -r --delete-after --quiet output/ app@${SERVER_IP_ADDRESS}:./${APP_PREFIX}
